apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "app.name" . }}
    tag: {{ .Values.image.tag }}
  name: {{ include "app.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
      tag: {{ .Values.image.tag }}
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
        tag: {{ .Values.image.tag }}
    spec:
      containers:
      - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "app.name" . }}
        resources: {{ .Values.resources }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  