apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "app.name" . }}
    tag: {{ .Values.image.tag}}
  name: {{ include "app.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "app.name" . }}
    tag: {{ .Values.image.tag }}
  type: {{ .Values.service.type }}
