apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-nginx-staging
  namespace: {{ .Values.argoCDNamespace }}
spec:
  destination:
    namespace: helm-nginx-staging
    server: {{ .Values.serverUrl }}
  project: {{ .Values.project }}
  source:
    helm:
      valueFiles:
        - ../vars/values-staging.yaml
    path: child-apps/helm-nginx/chart
    repoURL: {{ .Values.repoUrl }}
    targetRevision: {{ .Values.revision }}
  syncPolicy: {}