apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-python-helloworld
  namespace: {{ .Values.argoCDNamespace }}
spec:
  destination:
    namespace: simple-python-helloworld
    server: {{ .Values.serverUrl }}
  project: {{ .Values.project }}
  source:
    path: child-apps/python-helloworld
    repoURL: {{ .Values.repoUrl }}
    targetRevision: {{ .Values.revision }}
  syncPolicy:
    syncOptions:     # Sync options which modifies sync behavior
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    